services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["/bin/sh", "-c", "sleep 5 && npx prisma generate && npx prisma migrate deploy && npm run start:dev"]

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "5173:5173"

volumes:
  pgdata:
